from collections.abc import Iterable
from datetime import date, datetime
from typing import Protocol
from uuid import UUID

from paybridge.domain.enums import PaymentState, Rail
from paybridge.domain.models import (
    Payment,
    PaymentTransition,
    RailResponse,
    Refund,
    RoutingDecision,
    SettlementEntry,
)


class PaymentRepository(Protocol):
    def reserve_and_append_payment(
        self,
        payment: Payment,
        decision: RoutingDecision | None = None,
        correlation_id: str | None = None,
    ) -> tuple[bool, UUID]: ...
    def get_payment(self, payment_id: UUID) -> Payment: ...
    def get_current_state(self, payment_id: UUID) -> PaymentState: ...
    def append_transition(self, transition: PaymentTransition, correlation_id: str | None = None) -> None: ...
    def latest_transition(self, payment_id: UUID) -> PaymentTransition | None: ...
    def count_payments_for_key(self, key: str) -> int: ...
    def list_payments(self, actor: str | None = None) -> list[Payment]: ...
    def list_transitions(self, payment_id: UUID) -> list[PaymentTransition]: ...
    def list_settled(self, business_date: date) -> list[Payment]: ...


class RoutingRepository(Protocol):
    def append_decision(self, decision: RoutingDecision) -> None: ...
    def get_route(self, payment_id: UUID) -> Rail | None: ...


class AuditRepository(Protocol):
    def append_transition_audit(self, transition: PaymentTransition, correlation_id: str) -> None: ...
    def append_routing_audit(self, decision: RoutingDecision, correlation_id: str) -> None: ...
    def append_event(
        self, event_type: str, actor: str, correlation_id: str, payment_id: UUID | None, payload: dict[str, str]
    ) -> None: ...


class RailAdapter(Protocol):
    rail: Rail

    def submit(self, payment: Payment, attempt: int) -> RailResponse: ...


class RailReferenceLookup(Protocol):
    def payment_ids_by_reference(self, references: Iterable[str]) -> dict[str, UUID]: ...


class SettlementRepository(Protocol):
    def append_entries(self, entries: list[SettlementEntry]) -> None: ...
    def import_entries(
        self, entries: list[SettlementEntry], checksum: str, business_date: date, actor: str
    ) -> None: ...
    def append_reconciliation_result(self, result: SettlementEntry) -> bool: ...
    def list_reconciliation_results(self, business_date: date) -> list[SettlementEntry]: ...
    def list_entries(self, business_date: date) -> list[SettlementEntry]: ...
    def settlement_exists(self, business_date: date) -> bool: ...
    def append_file_record(self, business_date: date, path: str, checksum: str) -> None: ...


class RefundRepository(Protocol):
    def append_refund(self, refund: Refund, correlation_id: str | None = None) -> None: ...
    def get_refund(self, refund_id: UUID) -> Refund | None: ...
    def get_refund_for_payment(self, payment_id: UUID) -> Refund | None: ...
    def complete_refund(
        self, refund: Refund, transition: PaymentTransition, currency: str, correlation_id: str
    ) -> None: ...
    def fail_refund(
        self, refund: Refund, reason: str, actor: str, correlation_id: str, at: datetime
    ) -> None: ...
    def list_refunds(self) -> list[Refund]: ...
