from datetime import date
from decimal import Decimal
from typing import Protocol
from uuid import UUID

from paybridge.domain.enums import PaymentState, Rail, Role
from paybridge.domain.models import Payment, PaymentTransition, RailResponse, Refund, RoutingDecision, SettlementEntry


class PaymentRepository(Protocol):
    def reserve_and_append_payment(self, payment: Payment) -> tuple[bool, UUID]: ...
    def append_payment(self, payment: Payment) -> None: ...
    def get_payment(self, payment_id: UUID) -> Payment: ...
    def get_current_state(self, payment_id: UUID) -> PaymentState: ...
    def append_transition(self, transition: PaymentTransition) -> None: ...
    def count_payments_for_key(self, key: str) -> int: ...
    def list_payments(self, actor: str | None = None) -> list[Payment]: ...
    def list_transitions(self, payment_id: UUID) -> list[PaymentTransition]: ...
    def list_settled(self, business_date: date) -> list[Payment]: ...


class RoutingRepository(Protocol):
    def append_decision(self, decision: RoutingDecision) -> None: ...
    def get_route(self, payment_id: UUID) -> Rail | None: ...


class AuditRepository(Protocol):
    def append_transition_audit(self, transition: PaymentTransition, correlation_id: str) -> None: ...
    def append_routing_audit(self, decision: RoutingDecision, correlation_id: str) -> None: ...
    def append_event(self, event_type: str, actor: str, correlation_id: str, payment_id: UUID | None, payload: dict[str, str]) -> None: ...


class RailAdapter(Protocol):
    rail: Rail
    def submit(self, payment: Payment, attempt: int) -> RailResponse: ...


class RailAttemptRepository(Protocol):
    def list_attempts(self, payment_id: UUID) -> list[dict[str, str]]: ...


class SettlementRepository(Protocol):
    def append_entries(self, entries: list[SettlementEntry]) -> None: ...
    def append_reconciliation_result(self, result: SettlementEntry) -> None: ...
    def list_reconciliation_results(self, business_date: date) -> list[SettlementEntry]: ...
    def list_entries(self, business_date: date) -> list[SettlementEntry]: ...
    def settlement_exists(self, business_date: date) -> bool: ...
    def append_file_record(self, business_date: date, path: str, checksum: str) -> None: ...


class RefundRepository(Protocol):
    def append_refund(self, refund: Refund) -> None: ...
    def list_refunds(self) -> list[Refund]: ...


class UserDirectory(Protocol):
    def authenticate(self, token: str) -> tuple[str, Role]: ...
